	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DARKNESS_ENERGY             ; $07
	const DOUBLE_COLORLESS_ENERGY     ; $08
	const BULBASAUR                   ; $09
	const IVYSAUR                     ; $0a
	const VENUSAUR_LV64               ; $0b
	const VENUSAUR_LV67               ; $0c
	const CATERPIE                    ; $0d
	const METAPOD                     ; $0e
	const BUTTERFREE                  ; $0f
	const WEEDLE                      ; $10
	const KAKUNA                      ; $11
	const BEEDRILL                    ; $12
	const EKANS                       ; $13
	const ARBOK                       ; $14
	const NIDORANF                    ; $15
	const NIDORINA                    ; $16
	const NIDOQUEEN                   ; $17
	const NIDORANM                    ; $18
	const NIDORINO                    ; $19
	const NIDOKING                    ; $1a
	const ZUBAT                       ; $1b
	const GOLBAT                      ; $1c
	const ODDISH                      ; $1d
	const GLOOM                       ; $1e
	const VILEPLUME                   ; $1f
	const PARAS                       ; $20
	const PARASECT                    ; $21
	const VENONAT                     ; $22
	const VENOMOTH                    ; $23
	const BELLSPROUT                  ; $24
	const WEEPINBELL                  ; $25
	const VICTREEBEL                  ; $26
	const GRIMER                      ; $27
	const MUK                         ; $28
	const EXEGGCUTE                   ; $29
	const EXEGGUTOR                   ; $2a
	const KOFFING                     ; $2b
	const WEEZING                     ; $2c
	const TANGELA_LV8                 ; $2d
	const TANGELA_LV12                ; $2e
	const SCYTHER                     ; $2f
	const PINSIR                      ; $30
	const CHARMANDER                  ; $31
	const CHARMELEON                  ; $32
	const CHARIZARD                   ; $33
	const VULPIX                      ; $34
	const NINETALES_LV32              ; $35
	const NINETALES_LV35              ; $36
	const GROWLITHE                   ; $37
	const ARCANINE_LV34               ; $38
	const ARCANINE_LV45               ; $39
	const PONYTA                      ; $3a
	const RAPIDASH                    ; $3b
	const MAGMAR_LV24                 ; $3c
	const MAGMAR_LV31                 ; $3d
	const FLAREON_LV22                ; $3e
	const FLAREON_LV28                ; $3f
	const MOLTRES_LV35                ; $40
	const MOLTRES_LV37                ; $41
	const SQUIRTLE                    ; $42
	const WARTORTLE                   ; $43
	const BLASTOISE                   ; $44
	const PSYDUCK                     ; $45
	const GOLDUCK                     ; $46
	const POLIWAG                     ; $47
	const POLIWHIRL                   ; $48
	const POLIWRATH                   ; $49
	const TENTACOOL                   ; $4a
	const TENTACRUEL                  ; $4b
	const SEEL                        ; $4c
	const DEWGONG                     ; $4d
	const SHELLDER                    ; $4e
	const CLOYSTER                    ; $4f
	const KRABBY                      ; $50
	const KINGLER                     ; $51
	const HORSEA                      ; $52
	const SEADRA                      ; $53
	const GOLDEEN                     ; $54
	const SEAKING                     ; $55
	const STARYU                      ; $56
	const STARMIE                     ; $57
	const MAGIKARP                    ; $58
	const GYARADOS                    ; $59
	const LAPRAS                      ; $5a
	const VAPOREON_LV29               ; $5b
	const VAPOREON_LV42               ; $5c
	const OMANYTE                     ; $5d
	const OMASTAR                     ; $5e
	const ARTICUNO_LV35               ; $5f
	const ARTICUNO_LV37               ; $60
	const PIKACHU_LV12                ; $61
	const PIKACHU_LV16                ; $62
	const FLYING_PIKACHU              ; $63
	const SURFING_PIKACHU_LV13        ; $64
	const RAICHU_LV35                 ; $65
	const RAICHU_LV40                 ; $66
	const RAICHU_LV45                 ; $67
	const MAGNEMITE_LV15              ; $68
	const MAGNETON_LV28               ; $69
	const MAGNETON_LV35               ; $6a
	const VOLTORB                     ; $6b
	const ELECTRODE_LV35              ; $6c
	const ELECTRODE_LV42              ; $6d
	const ELECTABUZZ_LV20             ; $6e
	const ELECTABUZZ_LV35             ; $6f
	const JOLTEON_LV24                ; $70
	const JOLTEON_LV29                ; $71
	const ZAPDOS_LV40                 ; $72
	const ZAPDOS_LV64                 ; $73
	const ZAPDOS_LV68                 ; $74
	const SANDSHREW                   ; $75
	const SANDSLASH                   ; $76
	const DIGLETT                     ; $77
	const DUGTRIO                     ; $78
	const MANKEY                      ; $79
	const PRIMEAPE                    ; $7a
	const MACHOP                      ; $7b
	const MACHOKE                     ; $7c
	const MACHAMP                     ; $7d
	const GEODUDE                     ; $7e
	const GRAVELER                    ; $7f
	const GOLEM                       ; $80
	const ONIX                        ; $81
	const CUBONE                      ; $82
	const MAROWAK_LV26                ; $83
	const MAROWAK_LV32                ; $84
	const HITMONLEE                   ; $85
	const HITMONCHAN                  ; $86
	const RHYHORN                     ; $87
	const RHYDON                      ; $88
	const KABUTO                      ; $89
	const KABUTOPS                    ; $8a
	const AERODACTYL                  ; $8b
	const ABRA                        ; $8c
	const KADABRA                     ; $8d
	const ALAKAZAM                    ; $8e
	const SLOWPOKE_LV9                ; $8f
	const SLOWBRO                     ; $90
	const GASTLY_LV8                  ; $91
	const GASTLY_LV17                 ; $92
	const HAUNTER_LV17                ; $93
	const HAUNTER_LV22                ; $94
	const GENGAR                      ; $95
	const DROWZEE                     ; $96
	const HYPNO                       ; $97
	const MR_MIME                     ; $98
	const JYNX                        ; $99
	const MEWTWO_LV53                 ; $9a
	const MEWTWO_LV60                 ; $9b
	const MEWTWO_ALT_LV60             ; $9c
	const MEW_LV8                     ; $9d
	const MEW_LV15                    ; $9e
	const MEW_LV23                    ; $9f
	const PIDGEY                      ; $a0
	const PIDGEOTTO                   ; $a1
	const PIDGEOT_LV38                ; $a2
	const PIDGEOT_LV40                ; $a3
	const RATTATA                     ; $a4
	const RATICATE                    ; $a5
	const SPEAROW                     ; $a6
	const FEAROW                      ; $a7
	const CLEFAIRY                    ; $a8
	const CLEFABLE                    ; $a9
	const JIGGLYPUFF                  ; $aa
	const WIGGLYTUFF_LV28             ; $ab
	const WIGGLYTUFF_LV36             ; $ac
	const MEOWTH_LV15                 ; $ad
	const PERSIAN                     ; $ae
	const FARFETCHD                   ; $af
	const DODUO                       ; $b0
	const DODRIO                      ; $b1
	const LICKITUNG                   ; $b2
	const CHANSEY                     ; $b3
	const KANGASKHAN                  ; $b4
	const TAUROS                      ; $b5
	const DITTO                       ; $b6
	const EEVEE                       ; $b7
	const PORYGON                     ; $b8
	const SNORLAX                     ; $b9
	const DRATINI                     ; $ba
	const DRAGONAIR                   ; $bb
	const DRAGONITE_LV41              ; $bc
	const DRAGONITE_LV45              ; $bd
	const PROFESSOR_OAK               ; $be
	const IMPOSTER_PROFESSOR_OAK      ; $bf
	const BILL                        ; $c0
	const MR_FUJI                     ; $c1
	const LASS                        ; $c2
	const IMAKUNI_CARD                ; $c3
	const POKEMON_TRADER              ; $c4
	const POKEMON_BREEDER             ; $c5
	const CLEFAIRY_DOLL               ; $c6
	const MYSTERIOUS_FOSSIL           ; $c7
	const ENERGY_RETRIEVAL            ; $c8
	const ENERGY_RECYCLER             ; $c9
	const ENERGY_SEARCH               ; $ca
	const ENERGY_REMOVAL              ; $cb
	const ENERGY_SWITCH               ; $cc
	const SWITCH                      ; $cd
	const POKEMON_CENTER              ; $ce
	const POKE_BALL                   ; $cf
	const SCOOP_UP                    ; $d0
	const COMPUTER_SEARCH             ; $d1
	const POKEDEX                     ; $d2
	const PLUSPOWER                   ; $d3
	const DEFENDER                    ; $d4
	const ITEM_FINDER                 ; $d5
	const GIOVANNI                    ; $d6
	const DEVOLUTION_SPRAY            ; $d7
	const POTION                      ; $d8
	const SUPER_POTION                ; $d9
	const FULL_HEAL                   ; $da
	const REVIVE                      ; $db
	const MAINTENANCE                 ; $dc
	const POKEMON_FLUTE               ; $dd
	const GAMBLER                     ; $de
	const RECYCLE                     ; $df
	const RARE_CANDY                  ; $e0
	const POKEMON_NURSE               ; $e1
DEF NUM_CARDS EQU const_value - 1

DEF ENERGY_IDS_START  EQU GRASS_ENERGY
DEF POKEMON_IDS_START EQU BULBASAUR
DEF TRAINER_IDS_START EQU PROFESSOR_OAK
